version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    networks:
      - backend
    expose:
      - 5432:5432
    volumes: 
      - /opt/docker-volumes/postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: login@mail
      PGADMIN_DEFAULT_PASSWORD: password
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: websecure
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.you-name.it`)
      traefik.http.routers.pgadmin.tls: true
      traefik.http.routers.pgadmin.tls.certresolver: letsencrypt
      traefik.http.routers.pgadmin.service: pgadmin
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
      traefik.docker.network: backend
volumes:
  db:
    driver: local

networks:
  backend:
    name: traefik-portainer_backend
    external: true
